# Introduction to 1D NumPy arrays

NumPy is what allowed Python to any kind of Data Analysis.

NumPy is a module and so we NEED to import NumPy in order to use any of its objects, functions, or data types.

In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


## NumPy 1D Arrays

The **ndarray** is the work horse of NumPy. We will start with the simplest version known as a 1D array.

### Create 1D arrays

In [4]:
range(6)

range(0, 6)

In [5]:
type( range(6) )

range

In [6]:
list( range(6) )

[0, 1, 2, 3, 4, 5]

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [8]:
a = np.arange(6)

In [9]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int64`, 48 bytes
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


In [10]:
type( a )

numpy.ndarray

In [11]:
type( list(range(6)) )

list

In [12]:
a_list = list( range(6) ) 

In [13]:
type( a_list )

list

In [14]:
dir( a_list )

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [15]:
dir( a )

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


BUT...one thing that is SIMILAR between lists and NumPy arrays is that we can SLICE/INDEX both objects!

In [16]:
a_list[0]

0

In [17]:
a[0]

np.int64(0)

In [18]:
a_list[-1]

5

In [19]:
a[-1]

np.int64(5)

In [20]:
a_list[ :3 ]

[0, 1, 2]

In [21]:
a[ :3 ]

array([0, 1, 2])

In [22]:
print( a[ :3 ] )

[0 1 2]


In [23]:
a_list[ 1:3 ]

[1, 2]

In [24]:
a[ 1:3 ]

array([1, 2])

### Attributes

In [25]:
len( a_list )

6

But with NumPy arrays we can instead use ATTRIBUTES to identify the NUMBER of dimensions, the number of elements per dimension, and the total SIZE in the array.

In [26]:
a.ndim

1

In [27]:
a.shape

(6,)

In [28]:
type( a.shape )

tuple

In [29]:
a.size

6

In [30]:
a

array([0, 1, 2, 3, 4, 5])

### Other ways to create arrays

One way to make an array is with the `np.array()` function. This lets us CONVERT a LIST or a TUPLE to an array.

In [ ]:
[1, 2, 3, 4, 5]

In [ ]:
type( [1, 2, 3, 4, 5] )

In [ ]:
np.array( [1, 2, 3, 4, 5] )

In [ ]:
a1 = np.array( [ 1, 2, 3, 4, 5] )

In [ ]:
%whos

In [ ]:
a1.ndim

In [ ]:
a1.shape

In [ ]:
a1.size

In [ ]:
a1

In [ ]:
print( a1 )

In [ ]:
a2 = np.array( (1, 2, 3, 4, 5) )

In [ ]:
a2

In [ ]:
%whos

In [ ]:
a2.ndim

In [ ]:
a2.shape

In [ ]:
a2.size

There are speciality functions for creating arrays of 1 value.

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
0 * np.arange(5)

array([0, 0, 0, 0, 0])

### NumPy Constants
The NumPy library has many useful mathematical and scientific constants you can use in your programs

In [34]:
print(np.inf) # infinity

inf


In [35]:
print(-np.inf) # negative infinity

-inf


In [36]:
print(np.e) # euler

2.718281828459045


In [38]:
print(np.euler_gamma) # euler gamma

0.5772156649015329


In [39]:
print(np.pi) # pi

3.141592653589793


The `np.arange()` function has 3 arguments.

START, STOP (EXCLUSIVE), and STEP.

In [40]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [41]:
np.arange(0, 6, 3)

array([0, 3])

In [42]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [ ]:
np.arange(0, 100, 20)

In [ ]:
np.arange(0, 100+1, 20)

The `np.linspace()` function is very similar to `np.arange()` BUT...

START, STOP (INCLUSIVE), and Number of points.

In [43]:
np.linspace(0, 6, num=1)

array([0.])

In [44]:
np.linspace(0, 6, num=6)

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [45]:
np.linspace(0, 6, num=6+1)

array([0., 1., 2., 3., 4., 5., 6.])

In [46]:
np.linspace(0, 6, num=20)

array([0.        , 0.31578947, 0.63157895, 0.94736842, 1.26315789,
       1.57894737, 1.89473684, 2.21052632, 2.52631579, 2.84210526,
       3.15789474, 3.47368421, 3.78947368, 4.10526316, 4.42105263,
       4.73684211, 5.05263158, 5.36842105, 5.68421053, 6.        ])

In [47]:
np.arange(-10, 10, 1.2)

array([-10. ,  -8.8,  -7.6,  -6.4,  -5.2,  -4. ,  -2.8,  -1.6,  -0.4,
         0.8,   2. ,   3.2,   4.4,   5.6,   6.8,   8. ,   9.2])

In [48]:
np.arange(-10, 10, 1.2).shape

(17,)

In [49]:
np.linspace(-10, 10, num=17)

array([-10.  ,  -8.75,  -7.5 ,  -6.25,  -5.  ,  -3.75,  -2.5 ,  -1.25,
         0.  ,   1.25,   2.5 ,   3.75,   5.  ,   6.25,   7.5 ,   8.75,
        10.  ])

In [50]:
np.linspace(-10, 10, num=17).shape

(17,)

## Differences with lists

Operators may behave differently on NumPy arrays compared to lists.

In [51]:
a_list

[0, 1, 2, 3, 4, 5]

In [52]:
a_list == [0, 1, 2, 3, 4, 5]

True

In [53]:
a

array([0, 1, 2, 3, 4, 5])

In [54]:
a == np.array([0, 1, 2, 3, 4, 5])

array([ True,  True,  True,  True,  True,  True])

In [55]:
a == np.array([-10, 1, 2, 3, 4, 5])

array([False,  True,  True,  True,  True,  True])

In [56]:
np.zeros(5) == np.zeros(10)

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

In [57]:
np.array_equal( a, np.array([0, 1, 2, 3, 4, 5]))

True

In [58]:
np.array_equal( a, np.array([-10, 1, 2, 3, 4, 5]))

False

The `+` operator behaves differently!!!

In [59]:
[1, 2, 3] + [3, 2, 1]

[1, 2, 3, 3, 2, 1]

In [60]:
np.array([1, 2, 3]) + np.array([3, 2, 1])

array([4, 4, 4])

In [61]:
np.zeros(5) + np.ones(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.zeros(10) + np.ones(5)

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [63]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# Introduction to 2D NumPy arrays

We saw how to create, manipulate, modify, organize, and summarize 1D arrays...but what does 1D even mean????

## Import NumPy

In [ ]:
import numpy as np

## List of lists

Return back to base Python to begin...we have made lists of lists before...

But this list of lists will be simple, just 2 elements. Each element will be a list of 3 values.

In [65]:
[ [0, 0, 0], [1, 1, 1] ]

[[0, 0, 0], [1, 1, 1]]

Do the same thing as above...but let's include in more white space and spacing!!!

In [66]:
[ [0, 0, 0], 
  [1, 1, 1] ]

[[0, 0, 0], [1, 1, 1]]

In [67]:
[ [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] ]

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

Let's assign our list of lists to an abject.

In [68]:
my_list_of_lists = [ [0, 0, 0], 
                     [1, 1, 1] ]

In [69]:
my_list_of_lists

[[0, 0, 0], [1, 1, 1]]

In [70]:
%whos

Variable           Type       Data/Info
---------------------------------------
a                  ndarray    6: 6 elems, type `int64`, 48 bytes
a_list             list       n=6
my_list_of_lists   list       n=2
np                 module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


In [71]:
len( my_list_of_lists )

2

Let's convert the list of lists to a NumPy array!!!!

In [72]:
my_array = np.array( my_list_of_lists )

In [73]:
type( my_array )

numpy.ndarray

In [74]:
my_array.ndim

2

In [75]:
my_array.shape

(2, 3)

In [76]:
my_array

array([[0, 0, 0],
       [1, 1, 1]])

2D arrays are MATRICES and they kind of look like TABLES.

2D arrays have 2 dimensions...they have ROWS and COLUMNS!!!!!!

In [77]:
my_array.shape

(2, 3)

In [78]:
my_array.shape[0]

2

In [79]:
my_array.shape[1]

3

In [80]:
my_array.size

6

In [81]:
my_array.shape[0] * my_array.shape[1]

6

But please remember the list of lists does NOT understand ROWS and COLUMNS.

In [ ]:
my_array_b = np.array( [ [0, 0, 0], [1, 1, 1] ] )

In [ ]:
my_array_b.ndim

In [ ]:
my_array_b.shape

In [ ]:
my_array_b.size

In [ ]:
my_array_b

Creating a 2D array from a list of lists requires each inner list to have the same length!!!

In [ ]:
np.array([ [0, 0, 0],
           [1, 1, 1, 1, 1, 1, 1] ])

A 2D array must have the same number of columns in each row!!!!!!!!!!

Alternatively, we can create 2D arrays by COMBINING 1D arrays!!!

In [82]:
a = np.zeros(3)

In [83]:
b = np.ones(3)

In [84]:
a.ndim

1

In [85]:
a.shape

(3,)

In [86]:
a

array([0., 0., 0.])

In [87]:
b.ndim

1

In [88]:
b.shape

(3,)

We can use the `np.concatenate()` function to combine the two 1D arrays.

In [89]:
np.concatenate( [a, b] )

array([0., 0., 0., 1., 1., 1.])

In [90]:
np.concatenate( [a, b] ).shape

(6,)

Creating a 2D array from 1D arrays requires changing the syntax to `np.concatenate()`.

In [91]:
np.concatenate( [ [a], [b] ] )

array([[0., 0., 0.],
       [1., 1., 1.]])

There are speciality functions that simplify STACKING arrays together!!!

Stacking arrays ON top of each other is known as VERTICAL stacking or VERTICAL combing.

In [92]:
np.vstack( [a, b] )

array([[0., 0., 0.],
       [1., 1., 1.]])

Combing arrays side by side is known as HORIZONTAL stacking.

In [93]:
np.hstack( [a, b] )

array([0., 0., 0., 1., 1., 1.])

We can combine or stack more than 2 arrays at the same time!

In [94]:
c = 2 * np.ones(3)

In [95]:
d = 3 * np.ones(3)

In [96]:
c

array([2., 2., 2.])

In [97]:
d

array([3., 3., 3.])

In [ ]:
np.vstack( [a, b, c, d] )

In [ ]:
np.vstack( [a, b, c, d] ).shape

We can also stack 2D arrays together!!

In [ ]:
np.vstack( [ np.vstack([a, b]), np.vstack([c,d]) ] )

# Generating random numbers with NumPy

NumPy greatly streamlines the process of generating many random numbers!

## Import NumPy

In [ ]:
import numpy as np

## Random number generators

NumPy has its own family of random number generators. It requires that we initialize or specify the GENERATOR object.

In [ ]:
rg = np.random.default_rng(12345)

In [ ]:
%whos

Generating random numbers requires calling methods associated with the generator object.

The uniform random number between 0 and 1 is created using the `rg.random()` method.

In [ ]:
rg.random()

In [ ]:
rg.random()

In [ ]:
rg.random()

Reseting the seed will allow us to reproduce the previous SEQUENCE of random numbers.

In [ ]:
rg = np.random.default_rng(12345)

print( rg.random(), rg.random(), rg.random() )

But, NumPy allows us to generate MANY random numbers in one function call!!!!

The `random` module required us to ITERATE via for-loops or list comprehensions to generate SEQUENCES of random numbers.

NumPy handles all of that for us!!!

In [ ]:
rg = np.random.default_rng(12345)

In [ ]:
rg.random( 3 )

This allows us to generate a LARGE number of values and summarize them easily!!

In [ ]:
rg.random( 1001 ).mean()

But...we can tell `rg.random()` to generate a 2D array!!!!!

In [ ]:
rg = np.random.default_rng(12345)

In [ ]:
rg.random( (4, 2) )

In [ ]:
rg.random( (1001, 5) ).shape

In [ ]:
rg.random( (5, 1001) ).shape

In [ ]:
rg.random( (10000, 500) ).shape

In [ ]:
rg.random( (10000, 500) ).size

## Other distributions

In [ ]:
help( np.random.random )

In [ ]:
help( np.random.normal )

To generate 7 random numbers from a Gaussian or Bell Curve with mean -100 and standard deviation 5:

In [ ]:
rg = np.random.default_rng(12345)

In [ ]:
rg.normal( -100, 5, 7 )

In [ ]:
rg.normal( -100, 5, (4, 2) )

In [ ]:
import numpy as np

## Define the random number generator

In [ ]:
rg = np.random.default_rng(1976)

In [ ]:
%whos

In [ ]:
rg = np.random.default_rng(1976)

rg.random( (Ns, nr) ).mean( axis = 0).std( ddof = 1 )

# RESHAPING with NumPy

We need to review DIMENSIONS or SHAPES in NumPy. What is the difference between ROWS and COLUMNS?

## Import Modules

In [ ]:
import numpy as np

## Introduction to reshaping

Let's begin be reviewing a 1D NumPy array.

In [ ]:
np.arange( 1, 25 )

In [ ]:
np.arange( 1, 25 ).ndim

In [ ]:
np.arange( 1, 25 ).shape

In [ ]:
np.arange( 1, 25 ).size

In [ ]:
x = np.arange( 1, 25 )

In [ ]:
%whos

In [ ]:
x

In [ ]:
x.size

In [ ]:
x.ndim

In [ ]:
x.shape

Let's convert or **RESHAPE** the 1D array into a 2D array!!!!

We will literally ADD a dimension to the object and thus modify where and how the values are stored!

We reshape with the `.reshape()` method. All NumPy arrays have the `.reshape()` method.

`.reshape( <NEW ROWS>, <NEW COLUMNS> )`

Let's convert the `x` into a 2D array with 12 rows and 2 columns.

In [ ]:
x

In [ ]:
x.reshape( 12, 2 )

In [ ]:
[ [1, 2],
  [3, 4], 
  [5, 6] ]

In [ ]:
x.reshape( 12, 2 ).ndim

The `.ndim` attribute is DIFFERENT AFTER applying the reshaping operation! Originally, the `x` object has 1 dimension:

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
x.reshape( 12, 2 ).shape

HOWEVER...VERY IMPORTANTLY...the TOTAL number of ELEMENTS has NOT changed!!!

In [ ]:
x.size

In [ ]:
x.reshape( 12, 2 ).size

In [ ]:
x

In [ ]:
x.reshape( 12, 2 )

In [ ]:
x2 = x.reshape( 12, 2 )

In [ ]:
x2

In [ ]:
x2[ :3, : ]

In [ ]:
x[ :3 ]

Of course, we could have reshaped to something other than 12 rows!

We could have reshaped to 6 rows and 4 columns!

In [ ]:
x.reshape( 6, 4 )

Or, I could do 4 rows and 6 columns!

In [ ]:
x.reshape( 4, 6 )

Or, 2 rows and 12 columns!

In [ ]:
x.reshape( 2, 12 )

In [ ]:
x.reshape( 2, 12 ).ndim

In [ ]:
x.reshape( 2, 12 ).shape

In [ ]:
x.reshape( 2, 12 ).size

I could even try 8 rows and 3 columns!

In [ ]:
x.reshape( 8, 3 )

Or 3 rows and 8 columns!

In [ ]:
x.reshape( 3, 8 )

The important point is that the NUMBER OF ROWS multiplied by the NUMBER OF COLUMNS must equal the total number of elements or SIZE!

If, you don't want to do the mental math and type both the NEW number of ROWS and the NEW number of COLUMNS...you can include a -1 as an argument.

In [ ]:
x.reshape( 12, -1 )

In [ ]:
x.reshape( 3, -1 )

In [ ]:
x.reshape( 3, -1 ).shape

In [ ]:
x.reshape( -1, 2 )

In [ ]:
x.reshape( -1, 8 )

PLEASE BE CAREFUL!!!!!!

In [ ]:
x.reshape( 9, -1 )

In [ ]:
x.reshape( 9, 3 )

In [ ]:
x.reshape( 9, 2 )

In [ ]:
x.reshape( 8, 4 )

The SIZE must equal the PRODUCT of the number of rows and the number of columns!

## Other reshaping procedures

The most common reshaping technique is the TRANSPOSE of a 2D array.

Transposing SWAPS the rows and the columns.

To see how to transpose let's work with a 2D array named `y`.

In [ ]:
y = np.arange( 1, 25 ).reshape( 8, -1 )

In [ ]:
y

In [ ]:
y.ndim

In [ ]:
%whos

In [ ]:
y.shape

NumPy 2D arrays include the `.T` attribute to EXECUTE a transpose.

In [ ]:
y.T

In [ ]:
y

In [ ]:
y.shape

In [ ]:
y.T.shape

Transposing is unfortunately what a lot of people will think of when you say RESHAPING the array!

But the `.reshape()` method is FAR MORE GENERAL than just TRANSPOSING!!

In [ ]:
y

In [ ]:
y.T

In [ ]:
y.reshape( 12, 2 )

In [ ]:
y.reshape( 4, 6 )

In fact the `.reshape()` is so general we can even turn a 2D array into a SINGLE ROW or SINGLE COLUMN object!!

In [ ]:
y

In [ ]:
y.reshape( 1, -1 )

In [ ]:
y.reshape( -1, 1 )

In [ ]:
x

In [ ]:
y.reshape( 1, -1 )

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
y.reshape( 1, -1 ).ndim

In [ ]:
y.reshape( 1, -1 ).shape

Sometimes we need to DROP a 2D array DOWN to a 1D array.

We can do that with the `.ravel()` method.

In [ ]:
x

In [ ]:
x.ndim

In [ ]:
y.reshape( 1, -1 ).shape

In [ ]:
y.reshape( 1, -1 ).ravel()

In [ ]:
y.reshape( 1, -1 ).ravel().shape

In [ ]:
y.reshape( 1, -1 ).ravel().ndim

In [ ]:
y.reshape( -1, 1 ).ravel()

In [ ]:
y.reshape( -1, 1 ).ravel().ndim

In [ ]:
y.reshape( -1, 1 ).ravel().shape

## Summary

We need to pay close attention to the number of ROWS and COLUMNS or the DIMENSIONS and SHAPE of the NumPy array!!!

We can modify the SHAPE by `.reshape()` and we can "SQUEEZE" or "compress" a 2D array into a 1D array with `.ravel()`.