## CMPINF 2100 Week 03

### Introduction to 1D NumPy arrays

NumPy is what allowed Python to any kind of Data Analysis.

NumPy is a module and so we NEED to import NumPy in order to use any of its objects, functions, or data types.

In [1]:
import numpy as np

In [2]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


## NumPy 1D Arrays

The **ndarray** is the work horse of NumPy. We will start with the simplest version known as a 1D array.

### Create 1D arrays

In [3]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [4]:
range(6)

range(0, 6)

In [5]:
type( range(6) )

range

In [6]:
list( range(6) )

[0, 1, 2, 3, 4, 5]

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [8]:
a = np.arange(6)

In [9]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [10]:
type( a )

numpy.ndarray

In [11]:
type( list(range(6)) )

list

In [12]:
a_list = list( range(6) ) 

In [13]:
type( a_list )

list

In [14]:
dir( a_list )

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [15]:
dir( a )

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

BUT...one thing that is SIMILAR between lists and NumPy arrays is that we can SLICE/INDEX both objects!

In [16]:
a_list[0]

0

In [17]:
a[0]

0

In [18]:
a_list[-1]

5

In [19]:
a[-1]

5

In [20]:
a_list[ :3 ]

[0, 1, 2]

In [21]:
a[ :3 ]

array([0, 1, 2])

In [22]:
a_list[ 1:3 ]

[1, 2]

In [24]:
a[ 1:3 ]

array([1, 2])

### Attributes

In [25]:
len( a_list )

6

But with NumPy arrays we can instead use ATTRIBUTES to identify the NUMBER of dimensions, the number of elements per dimension, and the total SIZE in the array.

In [26]:
a.ndim

1

In [27]:
a.shape

(6,)

In [28]:
type( a.shape )

tuple

In [29]:
a.size

6

In [30]:
a

array([0, 1, 2, 3, 4, 5])

### Other ways to create arrays

One way to make an array is with the `np.array()` function. This lets us CONVERT a LIST or a TUPLE to an array.

In [31]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [32]:
type( [1, 2, 3, 4, 5] )

list

In [33]:
np.array( [1, 2, 3, 4, 5] )

array([1, 2, 3, 4, 5])

In [34]:
a1 = np.array( [ 1, 2, 3, 4, 5] )

In [35]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
a1         ndarray    5: 5 elems, type `int32`, 20 bytes
a_list     list       n=6
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [36]:
a1.ndim

1

In [37]:
a1.shape

(5,)

In [38]:
a1.size

5

In [39]:
a1

array([1, 2, 3, 4, 5])

In [40]:
print( a1 )

[1 2 3 4 5]


In [41]:
a2 = np.array( (1, 2, 3, 4, 5) )

In [42]:
a2

array([1, 2, 3, 4, 5])

In [43]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
a1         ndarray    5: 5 elems, type `int32`, 20 bytes
a2         ndarray    5: 5 elems, type `int32`, 20 bytes
a_list     list       n=6
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [44]:
a2.ndim

1

In [45]:
a2.shape

(5,)

In [46]:
a2.size

5

There are speciality functions for creating arrays of 1 value.

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
0 * np.arange(5)

array([0, 0, 0, 0, 0])

The `np.arange()` function has 3 arguments.

START, STOP (EXCLUSIVE), and STEP.

In [50]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [51]:
np.arange(0, 6, 3)

array([0, 3])

In [52]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [53]:
np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [54]:
np.arange(0, 100+1, 20)

array([  0,  20,  40,  60,  80, 100])

The `np.linspace()` function is very similar to `np.arange()` BUT...

START, STOP (INCLUSIVE), and Number of points.

In [55]:
np.linspace(0, 6, num=1)

array([0.])

In [56]:
np.linspace(0, 6, num=6)

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [57]:
np.linspace(0, 6, num=6+1)

array([0., 1., 2., 3., 4., 5., 6.])

In [58]:
np.linspace(0, 6, num=20)

array([0.        , 0.31578947, 0.63157895, 0.94736842, 1.26315789,
       1.57894737, 1.89473684, 2.21052632, 2.52631579, 2.84210526,
       3.15789474, 3.47368421, 3.78947368, 4.10526316, 4.42105263,
       4.73684211, 5.05263158, 5.36842105, 5.68421053, 6.        ])

In [59]:
np.arange(-10, 10, 1.2)

array([-10. ,  -8.8,  -7.6,  -6.4,  -5.2,  -4. ,  -2.8,  -1.6,  -0.4,
         0.8,   2. ,   3.2,   4.4,   5.6,   6.8,   8. ,   9.2])

In [60]:
np.arange(-10, 10, 1.2).shape

(17,)

In [61]:
np.linspace(-10, 10, num=17)

array([-10.  ,  -8.75,  -7.5 ,  -6.25,  -5.  ,  -3.75,  -2.5 ,  -1.25,
         0.  ,   1.25,   2.5 ,   3.75,   5.  ,   6.25,   7.5 ,   8.75,
        10.  ])

In [62]:
np.linspace(-10, 10, num=17).shape

(17,)

## Differences with lists

Operators may behave differently on NumPy arrays compared to lists.

In [63]:
a_list

[0, 1, 2, 3, 4, 5]

In [64]:
a_list == [0, 1, 2, 3, 4, 5]

True

In [65]:
a

array([0, 1, 2, 3, 4, 5])

In [66]:
a == np.array([0, 1, 2, 3, 4, 5])

array([ True,  True,  True,  True,  True,  True])

In [67]:
a == np.array([-10, 1, 2, 3, 4, 5])

array([False,  True,  True,  True,  True,  True])

In [68]:
np.zeros(5) == np.zeros(10)

C:\Users\jyurk\AppData\Local\Temp\ipykernel_26132\506179799.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.zeros(5) == np.zeros(10)


False

In [69]:
np.array_equal( a, np.array([0, 1, 2, 3, 4, 5]))

True

In [70]:
np.array_equal( a, np.array([-10, 1, 2, 3, 4, 5]))

False

The `+` operator behaves differently!!!

In [71]:
[1, 2, 3] + [3, 2, 1]

[1, 2, 3, 3, 2, 1]

In [72]:
np.array([1, 2, 3]) + np.array([3, 2, 1])

array([4, 4, 4])

In [73]:
np.zeros(5) + np.ones(5)

array([1., 1., 1., 1., 1.])

In [74]:
np.zeros(10) + np.ones(5)

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [75]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
np.ones(5)

array([1., 1., 1., 1., 1.])