## CMPINF 2100 Week 03

### Introduction to 2D NumPy arrays

We saw how to create, manipulate, modify, organize, and summarize 1D arrays...but what does 1D even mean????

## Import NumPy

In [1]:
import numpy as np

## List of lists

Return back to base Python to begin...we have made lists of lists before...

But this list of lists will be simple, just 2 elements. Each element will be a list of 3 values.

In [2]:
[ [0, 0, 0], [1, 1, 1] ]

[[0, 0, 0], [1, 1, 1]]

Do the same thing as above...but let's include in more white space and spacing!!!

In [3]:
[ [0, 0, 0], 
  [1, 1, 1] ]

[[0, 0, 0], [1, 1, 1]]

In [4]:
[ [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] ]

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

Let's assign our list of lists to an abject.

In [5]:
my_list_of_lists = [ [0, 0, 0], 
                     [1, 1, 1] ]

In [6]:
my_list_of_lists

[[0, 0, 0], [1, 1, 1]]

In [7]:
%whos

Variable           Type      Data/Info
--------------------------------------
my_list_of_lists   list      n=2
np                 module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [8]:
len( my_list_of_lists )

2

Let's convert the list of lists to a NumPy array!!!!

In [9]:
my_array = np.array( my_list_of_lists )

In [10]:
type( my_array )

numpy.ndarray

In [11]:
my_array.ndim

2

In [12]:
my_array.shape

(2, 3)

In [13]:
my_array

array([[0, 0, 0],
       [1, 1, 1]])

2D arrays are MATRICES and they kind of look like TABLES.

2D arrays have 2 dimensions...they have ROWS and COLUMNS!!!!!!

In [14]:
my_array.shape

(2, 3)

In [15]:
my_array.shape[0]

2

In [16]:
my_array.shape[1]

3

In [17]:
my_array.size

6

In [18]:
my_array.shape[0] * my_array.shape[1]

6

But please remember the list of lists does NOT understand ROWS and COLUMNS.

In [19]:
my_array_b = np.array( [ [0, 0, 0], [1, 1, 1] ] )

In [20]:
my_array_b.ndim

2

In [21]:
my_array_b.shape

(2, 3)

In [22]:
my_array_b.size

6

In [23]:
my_array_b

array([[0, 0, 0],
       [1, 1, 1]])

Creating a 2D array from a list of lists requires each inner list to have the same length!!!

In [24]:
np.array([ [0, 0, 0],
           [1, 1, 1, 1, 1, 1, 1] ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

A 2D array must have the same number of columns in each row!!!!!!!!!!

Alternatively, we can create 2D arrays by COMBINING 1D arrays!!!

In [25]:
a = np.zeros(3)

In [26]:
b = np.ones(3)

In [27]:
a.ndim

1

In [28]:
a.shape

(3,)

In [29]:
a

array([0., 0., 0.])

In [30]:
b.ndim

1

In [31]:
b.shape

(3,)

We can use the `np.concatenate()` function to combine the two 1D arrays.

In [32]:
np.concatenate( [a, b] )

array([0., 0., 0., 1., 1., 1.])

In [33]:
np.concatenate( [a, b] ).shape

(6,)

Creating a 2D array from 1D arrays requires changing the syntax to `np.concatenate()`.

In [34]:
np.concatenate( [ [a], [b] ] )

array([[0., 0., 0.],
       [1., 1., 1.]])

There are speciality functions that simplify STACKING arrays together!!!

Stacking arrays ON top of each other is known as VERTICAL stacking or VERTICAL combing.

In [35]:
np.vstack( [a, b] )

array([[0., 0., 0.],
       [1., 1., 1.]])

Combing arrays side by side is known as HORIZONTAL stacking.

In [36]:
np.hstack( [a, b] )

array([0., 0., 0., 1., 1., 1.])

We can combine or stack more than 2 arrays at the same time!

In [37]:
c = 2 * np.ones(3)

In [38]:
d = 3 * np.ones(3)

In [39]:
c

array([2., 2., 2.])

In [40]:
d

array([3., 3., 3.])

In [41]:
np.vstack( [a, b, c, d] )

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [42]:
np.vstack( [a, b, c, d] ).shape

(4, 3)

We can also stack 2D arrays together!!

In [43]:
np.vstack( [ np.vstack([a, b]), np.vstack([c,d]) ] )

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])