## CMPINF 2100 Week 03

### Generating random numbers with NumPy

NumPy greatly streamlines the process of generating many random numbers!

## Import NumPy

In [1]:
import numpy as np

## Random number generators

NumPy has its own family of random number generators. It requires that we initialize or specify the GENERATOR object.

In [2]:
rg = np.random.default_rng(12345)

In [3]:
%whos

Variable   Type         Data/Info
---------------------------------
np         module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
rg         Generator    Generator(PCG64)


Generating random numbers requires calling methods associated with the generator object.

The uniform random number between 0 and 1 is created using the `rg.random()` method.

In [4]:
rg.random()

0.22733602246716966

In [5]:
rg.random()

0.31675833970975287

In [6]:
rg.random()

0.7973654573327341

Reseting the seed will allow us to reproduce the previous SEQUENCE of random numbers.

In [7]:
rg = np.random.default_rng(12345)

print( rg.random(), rg.random(), rg.random() )

0.22733602246716966 0.31675833970975287 0.7973654573327341


But, NumPy allows us to generate MANY random numbers in one function call!!!!

The `random` module required us to ITERATE via for-loops or list comprehensions to generate SEQUENCES of random numbers.

NumPy handles all of that for us!!!

In [8]:
rg = np.random.default_rng(12345)

In [9]:
rg.random( 3 )

array([0.22733602, 0.31675834, 0.79736546])

This allows us to generate a LARGE number of values and summarize them easily!!

In [10]:
rg.random( 1001 ).mean()

0.49129676414051904

But...we can tell `rg.random()` to generate a 2D array!!!!!

In [11]:
rg = np.random.default_rng(12345)

In [12]:
rg.random( (4, 2) )

array([[0.22733602, 0.31675834],
       [0.79736546, 0.67625467],
       [0.39110955, 0.33281393],
       [0.59830875, 0.18673419]])

In [13]:
rg.random( (1001, 5) ).shape

(1001, 5)

In [14]:
rg.random( (5, 1001) ).shape

(5, 1001)

In [15]:
rg.random( (10000, 500) ).shape

(10000, 500)

In [16]:
rg.random( (10000, 500) ).size

5000000

## Other distributions

In [17]:
help( np.random.random )

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [18]:
help( np.random.normal )

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
     

To generate 7 random numbers from a Gaussian or Bell Curve with mean -100 and standard deviation 5:

In [19]:
rg = np.random.default_rng(12345)

In [20]:
rg.normal( -100, 5, 7 )

array([-107.11912518,  -93.68135771, -104.35330869, -101.29586617,
       -100.37671654, -103.70442326, -106.83896351])

In [21]:
rg.normal( -100, 5, (4, 2) )

array([[ -96.75553599,  -98.19470943],
       [-109.76431532,  -88.26295173],
       [ -95.15751547, -103.7969359 ],
       [ -95.48900863, -102.33476587]])