## CMPINF 2100 Week 04

### RESHAPING with NumPy

We need to review DIMENSIONS or SHAPES in NumPy. What is the difference between ROWS and COLUMNS?

## Import Modules

In [1]:
import numpy as np

## Introduction to reshaping

Let's begin be reviewing a 1D NumPy array.

In [2]:
np.arange( 1, 25 )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [3]:
np.arange( 1, 25 ).ndim

1

In [4]:
np.arange( 1, 25 ).shape

(24,)

In [5]:
np.arange( 1, 25 ).size

24

In [6]:
x = np.arange( 1, 25 )

In [7]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
x          ndarray    24: 24 elems, type `int32`, 96 bytes


In [8]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [9]:
x.size

24

In [10]:
x.ndim

1

In [11]:
x.shape

(24,)

Let's convert or **RESHAPE** the 1D array into a 2D array!!!!

We will literally ADD a dimension to the object and thus modify where and how the values are stored!

We reshape with the `.reshape()` method. All NumPy arrays have the `.reshape()` method.

`.reshape( <NEW ROWS>, <NEW COLUMNS> )`

Let's convert the `x` into a 2D array with 12 rows and 2 columns.

In [12]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
x.reshape( 12, 2 )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [15]:
[ [1, 2],
  [3, 4], 
  [5, 6] ]

[[1, 2], [3, 4], [5, 6]]

In [16]:
x.reshape( 12, 2 ).ndim

2

The `.ndim` attribute is DIFFERENT AFTER applying the reshaping operation! Originally, the `x` object has 1 dimension:

In [17]:
x.ndim

1

In [18]:
x.shape

(24,)

In [19]:
x.reshape( 12, 2 ).shape

(12, 2)

HOWEVER...VERY IMPORTANTLY...the TOTAL number of ELEMENTS has NOT changed!!!

In [20]:
x.size

24

In [21]:
x.reshape( 12, 2 ).size

24

In [22]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
x.reshape( 12, 2 )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [24]:
x2 = x.reshape( 12, 2 )

In [25]:
x2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [26]:
x2[ :3, : ]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
x[ :3 ]

array([1, 2, 3])

Of course, we could have reshaped to something other than 12 rows!

We could have reshaped to 6 rows and 4 columns!

In [30]:
x.reshape( 6, 4 )

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

Or, I could do 4 rows and 6 columns!

In [31]:
x.reshape( 4, 6 )

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

Or, 2 rows and 12 columns!

In [32]:
x.reshape( 2, 12 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
x.reshape( 2, 12 ).ndim

2

In [34]:
x.reshape( 2, 12 ).shape

(2, 12)

In [35]:
x.reshape( 2, 12 ).size

24

I could even try 8 rows and 3 columns!

In [36]:
x.reshape( 8, 3 )

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

Or 3 rows and 8 columns!

In [37]:
x.reshape( 3, 8 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

The important point is that the NUMBER OF ROWS multiplied by the NUMBER OF COLUMNS must equal the total number of elements or SIZE!

If, you don't want to do the mental math and type both the NEW number of ROWS and the NEW number of COLUMNS...you can include a -1 as an argument.

In [39]:
x.reshape( 12, -1 )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [40]:
x.reshape( 3, -1 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
x.reshape( 3, -1 ).shape

(3, 8)

In [43]:
x.reshape( -1, 2 )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [44]:
x.reshape( -1, 8 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

PLEASE BE CAREFUL!!!!!!

In [45]:
x.reshape( 9, -1 )

ValueError: cannot reshape array of size 24 into shape (9,newaxis)

In [46]:
x.reshape( 9, 3 )

ValueError: cannot reshape array of size 24 into shape (9,3)

In [47]:
x.reshape( 9, 2 )

ValueError: cannot reshape array of size 24 into shape (9,2)

In [48]:
x.reshape( 8, 4 )

ValueError: cannot reshape array of size 24 into shape (8,4)

The SIZE must equal the PRODUCT of the number of rows and the number of columns!

## Other reshaping procedures

The most common reshaping technique is the TRANSPOSE of a 2D array.

Transposing SWAPS the rows and the columns.

To see how to transpose let's work with a 2D array named `y`.

In [49]:
y = np.arange( 1, 25 ).reshape( 8, -1 )

In [50]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [51]:
y.ndim

2

In [52]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
x          ndarray    24: 24 elems, type `int32`, 96 bytes
x2         ndarray    12x2: 24 elems, type `int32`, 96 bytes
y          ndarray    8x3: 24 elems, type `int32`, 96 bytes


In [53]:
y.shape

(8, 3)

NumPy 2D arrays include the `.T` attribute to EXECUTE a transpose.

In [54]:
y.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23],
       [ 3,  6,  9, 12, 15, 18, 21, 24]])

In [55]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [56]:
y.shape

(8, 3)

In [57]:
y.T.shape

(3, 8)

Transposing is unfortunately what a lot of people will think of when you say RESHAPING the array!

But the `.reshape()` method is FAR MORE GENERAL than just TRANSPOSING!!

In [58]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [59]:
y.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23],
       [ 3,  6,  9, 12, 15, 18, 21, 24]])

In [60]:
y.reshape( 12, 2 )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [61]:
y.reshape( 4, 6 )

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In fact the `.reshape()` is so general we can even turn a 2D array into a SINGLE ROW or SINGLE COLUMN object!!

In [62]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [63]:
y.reshape( 1, -1 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [64]:
y.reshape( -1, 1 )

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [66]:
y.reshape( 1, -1 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
x.ndim

1

In [68]:
x.shape

(24,)

In [70]:
y.reshape( 1, -1 ).ndim

2

In [71]:
y.reshape( 1, -1 ).shape

(1, 24)

But later in the semester and especially in the classes that follow CMPINF 2100...the difference between a TRUE 1D array and a 2D array that is a single column/row will be important...

Sometimes we need to DROP a 2D array DOWN to a 1D array.

We can do that with the `.ravel()` method.

In [72]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [73]:
x.ndim

1

In [75]:
y.reshape( 1, -1 ).shape

(1, 24)

In [76]:
y.reshape( 1, -1 ).ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [77]:
y.reshape( 1, -1 ).ravel().shape

(24,)

In [78]:
y.reshape( 1, -1 ).ravel().ndim

1

In [80]:
y.reshape( -1, 1 ).ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [81]:
y.reshape( -1, 1 ).ravel().ndim

1

In [82]:
y.reshape( -1, 1 ).ravel().shape

(24,)

## Summary

We need to pay close attention to the number of ROWS and COLUMNS or the DIMENSIONS and SHAPE of the NumPy array!!!

We can modify the SHAPE by `.reshape()` and we can "SQUEEZE" or "compress" a 2D array into a 1D array with `.ravel()`.